### ISSUE TITLE
Previos button does not re-mark nodes in Fibonacci heap

### ISSUE THREAD

**Issue by KuceraMartin** [kuk0/alg-vis#17]
When a marked node is moved into the root list in `FibHeapDecrKey` after its child is removed, it is unmarked (method `unmarkCut` is called on the `BinHeapNode`).  When the "Previous" button is clicked, the node appears to be marked again visually (it becomes black) but the property `cut` of `BinHeapNode` is `false`, therefore the heap does not work properly when a child is removed again (the node is not moved into the root list, even though it should be)

**Comment by kuk0** [comment]
good catch!
in `BinHeapNode.storeState`, we also need to store the `cut` field and recover it in `restoreState`
do you wanna send a pull request or should i fix it myself?

**Comment by KuceraMartin** [comment]
Here is the PR. Also, when this issue is resolved, could you please upload a new version of the jar file to your website? I would like to send a link to some of my teachers at CTU FIT. :)
