### ISSUE TITLE
Incorrect binary value

### ISSUE THREAD

**Issue by ghost** [kuk0/alg-vis#20]
On the following page:
https://people.ksp.sk/~kuko/gnarley-trees/?page_id=310
There is an example of a binary representation of a binomial heap within the second bullet point.
The example states that ( 11 (decimal) = 1101 (binary) ).
This is incorrect.
The correct value for 11 (decimal) is 1011(binary).
Thank you for your time.
Take care.

**Comment by kuk0** [comment]
thanks, fixed
